-- Tabela: dados_cliente
CREATE TABLE IF NOT EXISTS dados_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefone TEXT NOT NULL UNIQUE,
    atendimento_ia BOOLEAN DEFAULT TRUE,
    responsavel_atual TEXT,
    assumido_em TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela: chat_messages
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT NOT NULL,
    agent_type TEXT, -- 'human', 'system', 'ia'
    agent_name TEXT,
    message TEXT,
    message_type TEXT DEFAULT 'text',
    event TEXT, -- 'assumido', 'reativado', etc.
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para performance (opcional, mas recomendado)
CREATE INDEX IF NOT EXISTS idx_dados_cliente_telefone ON dados_cliente(telefone);
CREATE INDEX IF NOT EXISTS idx_chat_messages_phone ON chat_messages(phone);
